### ISSUE TITLE
action is nil when a handler for action is invoked on iOS 8

### ISSUE THREAD

**Issue by azeml** [maicki/MISAlertController#5]
id handler = ^(MISAlertAction *action) {
    };
    [alertController addAction:[MISAlertAction actionWithTitle:@"title" style:UIAlertActionStyleDefault handler:handler]];

when a button is clicked and handler() is invoked, the action parameter is nil for whatever reason, I need it to control the behavior of the handler. This only happens on iOS 8. My project uses ARC.

**Comment by maicki** [comment]
Should be fixed within version 1.0.1
