### ISSUE TITLE
Need MISAlertController.alertController property be moved to header file

### ISSUE THREAD

**Issue by azeml** [maicki/MISAlertController#6]
I need an access to alertController property in order to use its popoverPresentationController in iOS 8 like this:
		MISAlertController *alertController = [MISAlertController alertControllerWithTitle:title message:nil preferredStyle:UIAlertControllerStyleActionSheet];
		if ([alertController.alertController isKindOfClass:[UIAlertController class]]) {
			UIAlertController *alertController = alertController.alertController;
			UIPopoverPresentationController *popPC = alertController.popoverPresentationController;
			popPC.delegate = self;
			popPC.sourceView = self.view;
			anchorView = myButton;
			popPC.sourceRect = [anchorView.superview convertRect:anchorView.frame toView:self.view];
			popPC.permittedArrowDirections = UIPopoverArrowDirectionAny;
		}

**Comment by maicki** [comment]
You don't need to have access to the alertController. Use the showFromSourceView:inViewController: animated: method from MISAlertController to show the alert controller as popover. Please also look into the example project.
